apiVersion: v1
kind: Service

metadata:
  name: todo-service
  namespace: todo-app

  labels:
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-microservices

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: todo-service

  ports:
    - name: http
      port: 5001
      targetPort: 5001
      protocol: TCP