apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: rabbitmq-pvc
  namespace: todo-app

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: todo-microservices

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi