apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: todo-app-ingress
  namespace: todo-app

  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: todo-microservices

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"

spec:
  ingressClassName: nginx

  rules:
    # - host: todo.local

      http:
        paths:

          # ==========================================
          # API
          # ==========================================

          - path: /api
            pathType: Prefix

            backend:
              service:
                name: gateway
                port:
                  number: 8000

          # ==========================================
          # Frontend
          # ==========================================

          - path: /
            pathType: Prefix

            backend:
              service:
                name: frontend
                port:
                  number: 3000