apiVersion: v1
kind: Service

metadata:
  name: gateway
  namespace: todo-app

  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: todo-microservices

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: gateway

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP