apiVersion: v1
kind: Secret

metadata:
  name: todo-app-secrets
  namespace: todo-app

  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: todo-microservices

type: Opaque

stringData:

  # PostgreSQL

  POSTGRES_PASSWORD: "CHANGE_ME"

  AUTH_DB_PASSWORD: "CHANGE_ME"

  NOTIFICATION_DB_PASSWORD: "CHANGE_ME"


  # RabbitMQ

  RABBITMQ_USER: "CHANGE_ME"

  RABBITMQ_PASSWORD: "CHANGE_ME"

  RABBITMQ_URL: "amqp://CHANGE_ME:CHANGE_ME@rabbitmq:5672"


  # Database URLs

  AUTH_DATABASE_URL: "postgresql://auth_user:CHANGE_ME@postgres:5432/auth_db"

  TODO_DATABASE_URL: "postgresql://todo_user:CHANGE_ME@postgres:5432/todo_db"

  NOTIFICATION_DATABASE_URL: "postgresql://notification_user:CHANGE_ME@postgres:5432/notification_db"


  # Auth Session

  SESSION_SECRET: "CHANGE_ME"

  SESSION_MAX_AGE: "604800000"


  # API Gateway

  GATEWAY_SECRET: "CHANGE_ME"


  # SMTP

  SMTP_HOST: "CHANGE_ME"

  SMTP_PORT: "587"

  SMTP_USER: "CHANGE_ME"

  SMTP_PASS: "CHANGE_ME"

  MAIL_FROM: "CHANGE_ME"