apiVersion: v1
kind: Secret

metadata:
  name: todo-app-secrets
  namespace: todo-app

  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: todo-microservices

type: Opaque

stringData:

  # PostgreSQL

  POSTGRES_PASSWORD: "todo_password"
  AUTH_DB_PASSWORD: "auth_password"
  NOTIFICATION_DB_PASSWORD: "notification_password"

  # RabbitMQ
  RABBITMQ_USER: "rabbit_user"
  RABBITMQ_PASSWORD: "rabbit_password"
  RABBITMQ_URL: "amqp://rabbit_user:rabbit_password@rabbitmq:5672"

  # Database URLs
  AUTH_DATABASE_URL: "postgresql://auth_user:auth_password@postgres:5432/auth_db"
  TODO_DATABASE_URL: "postgresql://todo_user:todo_password@postgres:5432/todo_db"
  NOTIFICATION_DATABASE_URL: "postgresql://notification_user:notification_password@postgres:5432/notification_db"

  # Auth Session
  SESSION_SECRET: "mySuperSecretKey123"
  SESSION_MAX_AGE: "604800000"

  # API Gateway
  GATEWAY_SECRET: "my-super-secret-key"

  # SMTP
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "sunnygupta6497@gmail.com"
  SMTP_PASS: "iazsmhthpzcmbymu"
  MAIL_FROM: "<sunnygupta6497@gmail.com>"
