apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: todo-app

  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-microservices

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: notification-service

  ports:
    - name: http
      port: 5002
      targetPort: 5002
      protocol: TCP