apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: redis-pvc
  namespace: todo-app

  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: todo-microservices

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi