apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: todo-app

  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-microservices

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: auth-service

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP